### ISSUE TITLE
Declare global variables

### ISSUE THREAD

**Issue by NicktheGeek** [studiopress/seo-data-transporter#1]
The themes, plugins, and platforms variables need to be declared global so they are in the global scope when used within a function

``` php
global $_seodt_themes, $_seodt_plugins, $_seodt_platforms;
```

**Comment by nathanrice** [comment]
Where does this not work? [This](https://github.com/copyblogger/seo-data-transporter/blob/develop/admin.php#L84) would indicate they're already acting as global, no?

**Comment by NicktheGeek** [comment]
@nathanrice I'm not sure why it isn't working in RM, but it doesn't act globally in RM. Maybe it is just a difference in the PHP version or maybe it is because the plugin is being run differently. What I know is adding global before those items are initially defined outside the function fixed it.

**Comment by rrennick** [comment]
> I'm not sure why it isn't working in RM, but it doesn't act globally in RM.

It's because the files are require( 'd inside a function. Regular WP plugins are loading in the main line PHP which makes any inline variable declarations automatically global.

**Comment by NicktheGeek** [comment]
@rrennick good point. Sometimes I forget how we are handling the loading. So can we make these variables global when they are initially invoked.

**Comment by nathanrice** [comment]
Yeah, it's sloppy to assign values to those variables outside a function anyway, so I'll create one, globalize them inside, and hook it to an appropriate action.

**Comment by nathanrice** [comment]
No more global vars.
407553099fe301e2e84ea0854b48125467384d9e
