### ISSUE TITLE
Develop: fatal error on Convert

### ISSUE THREAD

**Issue by dreamwhisper** [studiopress/seo-data-transporter#10]
Attempting to convert from Genesis to Yoast SEO, I got a fatal error after clicking `Convert`:

> Fatal error: Call to undefined function do_action_() in /home/dreamwhi/public_html/dev4/wp-content/plugins/seo-data-transporter/includes/class-seo-data-transporter-utility.php on line 129

**Comment by nathanrice** [comment]
ef4a2cb
