### ISSUE TITLE
Add support for SEO by Squirrly

### ISSUE THREAD

**Issue by nickcernis** [studiopress/seo-data-transporter#5]
A user requested support for Yoast SEO → SEO by Squirrly: https://wordpress.org/support/topic/seo-by-squirrly-support?replies=1#post-7679462:

> Hi, this looks like a great plugin. Would you consider support for exporting from Yoast SEO to [SEO by SQUIRRLY](https://wordpress.org/plugins/squirrly-seo/)? Is there anything I can do to help with this? Thanks.

**Comment by nickcernis** [comment]
No longer required. SEO by Squirrly apparently handles Yoast SEO import by default. https://wordpress.org/support/topic/seo-by-squirrly-support?replies=4#post-7684286

**Comment by slomeli79** [comment]
What about the reverse: exporting from Squirrly into any of the existing options?

**Comment by nickcernis** [comment]
@slomeli79 I recommend contacting Squirrly support to ask about their recommendations for migrating away: https://www.squirrly.co/more#page-block-h5qe73hzhslz11cueliejyvi
