### ISSUE TITLE
Please fix Add-Meta-Tags field names

### ISSUE THREAD

**Issue by gnotaras** [studiopress/seo-data-transporter#6]
Hello Nathan,

Thanks for this great plugin and also thanks for supporting Add-Meta-Tags.

It seems there is a problem with the Add-Meta-Tags field names. SEO-Data-Transporter uses the (very very) old `description` and `keywords` fields. The fields that are used by my plugin to store data [have changed](http://www.codetrax.org/projects/wp-add-meta-tags/wiki/Data_Storage#Custom-Fields) since a long time ago.

Several users have contacted me about SEO-Data-Transporter not being able to locate any Add-Meta-Tags data. I've even replied to a user on your plugin's support forum at wordpress org providing all the [necessary changes](https://wordpress.org/support/topic/add-meta-tags-not-finding-any-records?replies=6#post-6408619) in order to be able to locate the data.

I'd be grateful if you incorporated these changes into your plugin in one of the upcoming releases.

For convenience I re-post the required changes here as well. These involve changing lines ~~86-90~~ [96-99](https://github.com/copyblogger/seo-data-transporter/blob/develop/plugin.php#L96) of `plugin.php` to the following:

```
'Add Meta Tags' => array(
    'Custom Doctitle' => '_amt_title',
    'META Description' => '_amt_description',
    'META Keywords' => '_amt_keywords',
),
```

If a pull request would be more useful, please let me know so as to submit one.

IIRC, I had tried to contact you some times in the past about this issue, but perhaps I must had been doing it wrong :)

Thank you in advance. Please feel free to contact me for more info if needed!

Best Regards,
George

**Comment by gnotaras** [comment]
I'm a bit confused here.. I don't see @nathanrice among the people of the organization that owns this repository. Is this an official repo?

Thanks in advance.

**Comment by nathanrice** [comment]
407553099fe301e2e84ea0854b48125467384d9e
